# Generated by Django 4.1 on 2022-08-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Purpose',
            new_name='purpose',
        ),
    ]
