# Generated by Django 4.1 on 2022-08-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_purpose_team_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Today')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('T', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('S', 'Sunday')], default='M', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('identification', models.IntegerField()),
                ('attendance', models.BooleanField()),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
