# Generated by Django 4.1 on 2022-08-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_employees_delete_feeding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='day',
        ),
    ]
